import pickle
from pathlib import PurePath


def tranches_2d():
    """ Returns a dictionary with the names of zinc's 2D tranches

        Returns
        -------
        dict[str, list[str]]
    """
    return {'AA': ['AAAA', 'AAAB', 'AAAC', 'AAAD', 'AABA', 'AABB', 'AABD', 'AACA', 'AACB',
                   'AAEA', 'AAEB', 'AAED'],
            'AB': ['ABAA', 'ABAB', 'ABAC', 'ABAD', 'ABBA', 'ABBB', 'ABBD', 'ABCA', 'ABCB',
                   'ABCD', 'ABEA', 'ABEB', 'ABEC', 'ABED'],
            'AC': ['ACAA', 'ACAB', 'ACAC', 'ACAD', 'ACBA', 'ACBB', 'ACBC', 'ACBD', 'ACCA',
                   'ACCB', 'ACCD', 'ACEA', 'ACEB', 'ACEC', 'ACED'],
            'AD': ['ADAA', 'ADAB', 'ADAC', 'ADAD', 'ADBA', 'ADBB', 'ADBC', 'ADBD', 'ADCA',
                   'ADCB', 'ADCC', 'ADCD', 'ADEA', 'ADEB', 'ADEC', 'ADED'],
            'AE': ['AEAA', 'AEAB', 'AEAC', 'AEAD', 'AEBA', 'AEBB', 'AEBC', 'AEBD', 'AECA',
                   'AECB', 'AECD', 'AEEA', 'AEEB', 'AEEC', 'AEED'],
            'AF': ['AFAA', 'AFAB', 'AFAC', 'AFAD', 'AFBA', 'AFBB', 'AFBC', 'AFBD', 'AFCA',
                   'AFCB', 'AFCD', 'AFEA', 'AFEB', 'AFEC', 'AFED'],
            'AG': ['AGAA', 'AGAB', 'AGAC', 'AGAD', 'AGBA', 'AGBB', 'AGBD', 'AGCA', 'AGCB',
                   'AGCD', 'AGEA', 'AGEB', 'AGEC', 'AGED'],
            'AH': ['AHAA', 'AHAB', 'AHAC', 'AHAD', 'AHBA', 'AHBB', 'AHCA', 'AHCB', 'AHCD',
                   'AHEA', 'AHEB', 'AHEC', 'AHED'],
            'AI': ['AIAA', 'AIAB', 'AIAC', 'AIAD', 'AIBA', 'AIBB', 'AICA', 'AICB', 'AIEA',
                   'AIEB', 'AIED'],
            'AJ': ['AJAA', 'AJAB', 'AJEA', 'AJEB'],
            'AK': ['AKAA', 'AKAB', 'AKEA', 'AKEB'],
            'BA': ['BAAA', 'BAAB', 'BAAC', 'BAAD', 'BABA', 'BABB', 'BABC', 'BABD', 'BACA',
                   'BACB', 'BACD', 'BAEA', 'BAEB', 'BAED'],
            'BB': ['BBAA', 'BBAB', 'BBAC', 'BBAD', 'BBBA', 'BBBB', 'BBBC', 'BBBD', 'BBCA',
                   'BBCB', 'BBCD', 'BBEA', 'BBEB', 'BBEC', 'BBED'],
            'BC': ['BCAA', 'BCAB', 'BCAC', 'BCAD', 'BCBA', 'BCBB', 'BCBC', 'BCBD', 'BCCA',
                   'BCCB', 'BCCD', 'BCEA', 'BCEB', 'BCEC', 'BCED'],
            'BD': ['BDAA', 'BDAB', 'BDAC', 'BDAD', 'BDBA', 'BDBB', 'BDBC', 'BDBD', 'BDCA',
                   'BDCB', 'BDCC', 'BDCD', 'BDEA', 'BDEB', 'BDEC', 'BDED'],
            'BE': ['BEAA', 'BEAB', 'BEAC', 'BEAD', 'BEBA', 'BEBB', 'BEBC', 'BEBD', 'BECA',
                   'BECB', 'BECC', 'BECD', 'BEEA', 'BEEB', 'BEEC', 'BEED'],
            'BF': ['BFAA', 'BFAB', 'BFAC', 'BFAD', 'BFBA', 'BFBB', 'BFBC', 'BFBD', 'BFCA',
                   'BFCB', 'BFCC', 'BFCD', 'BFEA', 'BFEB', 'BFEC', 'BFED'],
            'BG': ['BGAA', 'BGAB', 'BGAC', 'BGAD', 'BGBA', 'BGBB', 'BGBC', 'BGBD', 'BGCA',
                   'BGCB', 'BGCC', 'BGCD', 'BGEA', 'BGEB', 'BGEC', 'BGED'],
            'BH': ['BHAA', 'BHAB', 'BHAC', 'BHAD', 'BHBA', 'BHBB', 'BHBD', 'BHCA', 'BHCB',
                   'BHCD', 'BHEA', 'BHEB', 'BHEC', 'BHED'],
            'BI': ['BIAA', 'BIAB', 'BIAC', 'BIAD', 'BIBA', 'BIBB', 'BIBD', 'BICA', 'BICB',
                   'BICC', 'BICD', 'BIEA', 'BIEB', 'BIEC', 'BIED'],
            'BJ': ['BJAA', 'BJAB', 'BJAC', 'BJAD', 'BJBA', 'BJBB', 'BJBD', 'BJCA', 'BJCB',
                   'BJCD', 'BJEA', 'BJEB', 'BJEC', 'BJED'],
            'BK': ['BKAA', 'BKAB', 'BKAD', 'BKBA', 'BKBB', 'BKCA', 'BKCB', 'BKEA', 'BKEB',
                   'BKED'],
            'CA': ['CAAA', 'CAAB', 'CAAC', 'CAAD', 'CABA', 'CABB', 'CABD', 'CACA', 'CACB',
                   'CACC', 'CACD', 'CAEA', 'CAEB', 'CAEC', 'CAED'],
            'CB': ['CBAA', 'CBAB', 'CBAC', 'CBAD', 'CBBA', 'CBBB', 'CBBC', 'CBBD', 'CBCA',
                   'CBCB', 'CBCD', 'CBEA', 'CBEB', 'CBEC', 'CBED'],
            'CC': ['CCAA', 'CCAB', 'CCAC', 'CCAD', 'CCBA', 'CCBB', 'CCBC', 'CCBD', 'CCCA',
                   'CCCB', 'CCCD', 'CCEA', 'CCEB', 'CCEC', 'CCED'],
            'CD': ['CDAA', 'CDAB', 'CDAC', 'CDAD', 'CDBA', 'CDBB', 'CDBC', 'CDBD', 'CDCA',
                   'CDCB', 'CDCC', 'CDCD', 'CDEA', 'CDEB', 'CDEC', 'CDED'],
            'CE': ['CEAA', 'CEAB', 'CEAC', 'CEAD', 'CEBA', 'CEBB', 'CEBC', 'CEBD', 'CECA',
                   'CECB', 'CECC', 'CECD', 'CEEA', 'CEEB', 'CEEC', 'CEED'],
            'CF': ['CFAA', 'CFAB', 'CFAC', 'CFAD', 'CFBA', 'CFBB', 'CFBC', 'CFBD', 'CFCA',
                   'CFCB', 'CFCC', 'CFCD', 'CFEA', 'CFEB', 'CFEC', 'CFED'],
            'CG': ['CGAA', 'CGAB', 'CGAC', 'CGAD', 'CGBA', 'CGBB', 'CGBC', 'CGBD', 'CGCA',
                   'CGCB', 'CGCC', 'CGCD', 'CGEA', 'CGEB', 'CGEC', 'CGED'],
            'CH': ['CHAA', 'CHAB', 'CHAC', 'CHAD', 'CHBA', 'CHBB', 'CHBC', 'CHBD', 'CHCA',
                   'CHCB', 'CHCD', 'CHEA', 'CHEB', 'CHEC', 'CHED'],
            'CI': ['CIAA', 'CIAB', 'CIAC', 'CIAD', 'CIBA', 'CIBB', 'CIBC', 'CIBD', 'CICA',
                   'CICB', 'CICC', 'CICD', 'CIEA', 'CIEB', 'CIEC', 'CIED'],
            'CJ': ['CJAA', 'CJAB', 'CJAC', 'CJAD', 'CJBA', 'CJBB', 'CJBD', 'CJCA', 'CJCB',
                   'CJCD', 'CJEA', 'CJEB', 'CJEC', 'CJED'],
            'CK': ['CKAA', 'CKAB', 'CKAC', 'CKAD', 'CKBA', 'CKBB', 'CKBD', 'CKCA', 'CKCB',
                   'CKCD', 'CKEA', 'CKEB', 'CKEC', 'CKED'],
            'DA': ['DAAA', 'DAAB', 'DAAD', 'DABA', 'DABB', 'DABD', 'DACA', 'DACB', 'DACD',
                   'DAEA', 'DAEB', 'DAED'],
            'DB': ['DBAA', 'DBAB', 'DBAC', 'DBAD', 'DBBA', 'DBBB', 'DBBD', 'DBCA', 'DBCB',
                   'DBCD', 'DBEA', 'DBEB', 'DBEC', 'DBED'],
            'DC': ['DCAA', 'DCAB', 'DCAC', 'DCAD', 'DCBA', 'DCBB', 'DCBD', 'DCCA', 'DCCB',
                   'DCCD', 'DCEA', 'DCEB', 'DCED'],
            'DD': ['DDAA', 'DDAB', 'DDAC', 'DDAD', 'DDBA', 'DDBB', 'DDBD', 'DDCA', 'DDCB',
                   'DDCD', 'DDEA', 'DDEB', 'DDEC', 'DDED'],
            'DE': ['DEAA', 'DEAB', 'DEAC', 'DEAD', 'DEBA', 'DEBB', 'DEBC', 'DEBD', 'DECA',
                   'DECB', 'DECD', 'DEEA', 'DEEB', 'DEEC', 'DEED'],
            'DF': ['DFAA', 'DFAB', 'DFAC', 'DFAD', 'DFBA', 'DFBB', 'DFBC', 'DFBD', 'DFCA',
                   'DFCB', 'DFCD', 'DFEA', 'DFEB', 'DFEC', 'DFED'],
            'DG': ['DGAA', 'DGAB', 'DGAC', 'DGAD', 'DGBA', 'DGBB', 'DGBC', 'DGBD', 'DGCA',
                   'DGCB', 'DGCD', 'DGEA', 'DGEB', 'DGEC', 'DGED'],
            'DH': ['DHAA', 'DHAB', 'DHAC', 'DHAD', 'DHBA', 'DHBB', 'DHBC', 'DHBD', 'DHCA',
                   'DHCB', 'DHCD', 'DHEA', 'DHEB', 'DHEC', 'DHED'],
            'DI': ['DIAA', 'DIAB', 'DIAC', 'DIAD', 'DIBA', 'DIBB', 'DIBC', 'DIBD', 'DICA',
                   'DICB', 'DICD', 'DIEA', 'DIEB', 'DIEC', 'DIED'],
            'DJ': ['DJAA', 'DJAB', 'DJAC', 'DJAD', 'DJBA', 'DJBB', 'DJBC', 'DJBD', 'DJCA',
                   'DJCB', 'DJCD', 'DJEA', 'DJEB', 'DJEC', 'DJED'],
            'DK': ['DKAA', 'DKAB', 'DKAC', 'DKAD', 'DKBA', 'DKBB', 'DKBD', 'DKCA', 'DKCB',
                   'DKCD', 'DKEA', 'DKEB', 'DKEC', 'DKED'],
            'EA': ['EAAA', 'EAAB', 'EAAC', 'EAAD', 'EABA', 'EABB', 'EABD', 'EACA', 'EACB',
                   'EACD', 'EAEA', 'EAEB', 'EAED'],
            'EB': ['EBAA', 'EBAB', 'EBAC', 'EBAD', 'EBBA', 'EBBB', 'EBBD', 'EBCA', 'EBCB',
                   'EBCD', 'EBEA', 'EBEB', 'EBED'],
            'EC': ['ECAA', 'ECAB', 'ECAC', 'ECAD', 'ECBA', 'ECBB', 'ECBC', 'ECBD', 'ECCA',
                   'ECCB', 'ECCD', 'ECEA', 'ECEB', 'ECED'],
            'ED': ['EDAA', 'EDAB', 'EDAC', 'EDAD', 'EDBA', 'EDBB', 'EDBD', 'EDCA', 'EDCB',
                   'EDCD', 'EDEA', 'EDEB', 'EDEC', 'EDED'],
            'EE': ['EEAA', 'EEAB', 'EEAC', 'EEAD', 'EEBA', 'EEBB', 'EEBC', 'EEBD', 'EECA',
                   'EECB', 'EECC', 'EECD', 'EEEA', 'EEEB', 'EEEC', 'EEED'],
            'EF': ['EFAA', 'EFAB', 'EFAC', 'EFAD', 'EFBA', 'EFBB', 'EFBD', 'EFCA', 'EFCB',
                   'EFCD', 'EFEA', 'EFEB', 'EFEC', 'EFED'],
            'EG': ['EGAA', 'EGAB', 'EGAC', 'EGAD', 'EGBA', 'EGBB', 'EGBC', 'EGBD', 'EGCA',
                   'EGCB', 'EGCC', 'EGCD', 'EGEA', 'EGEB', 'EGEC', 'EGED'],
            'EH': ['EHAA', 'EHAB', 'EHAC', 'EHAD', 'EHBA', 'EHBB', 'EHBC', 'EHBD', 'EHCA',
                   'EHCB', 'EHCD', 'EHEA', 'EHEB', 'EHEC', 'EHED'],
            'EI': ['EIAA', 'EIAB', 'EIAC', 'EIAD', 'EIBA', 'EIBB', 'EIBC', 'EIBD', 'EICA',
                   'EICB', 'EICD', 'EIEA', 'EIEB', 'EIEC', 'EIED'],
            'EJ': ['EJAA', 'EJAB', 'EJAC', 'EJAD', 'EJBA', 'EJBB', 'EJBC', 'EJBD', 'EJCA',
                   'EJCB', 'EJCD', 'EJEA', 'EJEB', 'EJEC', 'EJED'],
            'EK': ['EKAA', 'EKAB', 'EKAC', 'EKAD', 'EKBA', 'EKBB', 'EKBD', 'EKCA', 'EKCB',
                   'EKCD', 'EKEA', 'EKEB', 'EKEC', 'EKED'],
            'FA': ['FAAA', 'FAAB', 'FAAC', 'FAAD', 'FABA', 'FABB', 'FABD', 'FACA', 'FACB',
                   'FACD', 'FAEA', 'FAEB', 'FAEC', 'FAED'],
            'FB': ['FBAA', 'FBAB', 'FBAC', 'FBAD', 'FBBA', 'FBBB', 'FBBD', 'FBCA', 'FBCB',
                   'FBCC', 'FBCD', 'FBEA', 'FBEB', 'FBED'],
            'FC': ['FCAA', 'FCAB', 'FCAC', 'FCAD', 'FCBA', 'FCBB', 'FCBD', 'FCCA', 'FCCB',
                   'FCCD', 'FCEA', 'FCEB', 'FCEC', 'FCED'],
            'FD': ['FDAA', 'FDAB', 'FDAC', 'FDAD', 'FDBA', 'FDBB', 'FDBC', 'FDBD', 'FDCA',
                   'FDCB', 'FDCD', 'FDEA', 'FDEB', 'FDEC', 'FDED'],
            'FE': ['FEAA', 'FEAB', 'FEAC', 'FEAD', 'FEBA', 'FEBB', 'FEBC', 'FEBD', 'FECA',
                   'FECB', 'FECD', 'FEEA', 'FEEB', 'FEEC', 'FEED'],
            'FF': ['FFAA', 'FFAB', 'FFAC', 'FFAD', 'FFBA', 'FFBB', 'FFBC', 'FFBD', 'FFCA',
                   'FFCB', 'FFCD', 'FFEA', 'FFEB', 'FFEC', 'FFED'],
            'FG': ['FGAA', 'FGAB', 'FGAC', 'FGAD', 'FGBA', 'FGBB', 'FGBC', 'FGBD', 'FGCA',
                   'FGCB', 'FGCD', 'FGEA', 'FGEB', 'FGEC', 'FGED'],
            'FH': ['FHAA', 'FHAB', 'FHAC', 'FHAD', 'FHBA', 'FHBB', 'FHBD', 'FHCA', 'FHCB',
                   'FHCD', 'FHEA', 'FHEB', 'FHEC', 'FHED'],
            'FI': ['FIAA', 'FIAB', 'FIAC', 'FIAD', 'FIBA', 'FIBB', 'FIBD', 'FICA', 'FICB',
                   'FICD', 'FIEA', 'FIEB', 'FIEC', 'FIED'],
            'FJ': ['FJAA', 'FJAB', 'FJAC', 'FJAD', 'FJBA', 'FJBB', 'FJBC', 'FJBD', 'FJCA',
                   'FJCB', 'FJCD', 'FJEA', 'FJEB', 'FJEC', 'FJED'],
            'FK': ['FKAA', 'FKAB', 'FKAC', 'FKAD', 'FKBA', 'FKBB', 'FKBC', 'FKBD', 'FKCA',
                   'FKCB', 'FKCC', 'FKCD', 'FKEA', 'FKEB', 'FKEC', 'FKED'],
            'GA': ['GAAA', 'GAAB', 'GAAC', 'GAAD', 'GABA', 'GABB', 'GABD', 'GACA', 'GACB',
                   'GACD', 'GAEA', 'GAEB', 'GAEC', 'GAED'],
            'GB': ['GBAA', 'GBAB', 'GBAD', 'GBBA', 'GBBB', 'GBBD', 'GBCA', 'GBCB', 'GBCD',
                   'GBEA', 'GBEB', 'GBED'],
            'GC': ['GCAA', 'GCAB', 'GCAC', 'GCAD', 'GCBA', 'GCBB', 'GCBD', 'GCCA', 'GCCB',
                   'GCCD', 'GCEA', 'GCEB', 'GCED'],
            'GD': ['GDAA', 'GDAB', 'GDAC', 'GDAD', 'GDBA', 'GDBB', 'GDBD', 'GDCA', 'GDCB',
                   'GDCD', 'GDEA', 'GDEB', 'GDED'],
            'GE': ['GEAA', 'GEAB', 'GEAC', 'GEAD', 'GEBA', 'GEBB', 'GEBD', 'GECA', 'GECB',
                   'GECD', 'GEEA', 'GEEB', 'GEEC', 'GEED'],
            'GF': ['GFAA', 'GFAB', 'GFAC', 'GFAD', 'GFBA', 'GFBB', 'GFBD', 'GFCA', 'GFCB',
                   'GFCD', 'GFEA', 'GFEB', 'GFEC', 'GFED'],
            'GG': ['GGAA', 'GGAB', 'GGAC', 'GGAD', 'GGBA', 'GGBB', 'GGBC', 'GGBD', 'GGCA',
                   'GGCB', 'GGCC', 'GGCD', 'GGEA', 'GGEB', 'GGEC', 'GGED'],
            'GH': ['GHAA', 'GHAB', 'GHAC', 'GHAD', 'GHBA', 'GHBB', 'GHBD', 'GHCA', 'GHCB',
                   'GHCD', 'GHEA', 'GHEB', 'GHEC', 'GHED'],
            'GI': ['GIAA', 'GIAB', 'GIAC', 'GIAD', 'GIBA', 'GIBB', 'GIBC', 'GIBD', 'GICA',
                   'GICB', 'GICD', 'GIEA', 'GIEB', 'GIEC', 'GIED'],
            'GJ': ['GJAA', 'GJAB', 'GJAC', 'GJAD', 'GJBA', 'GJBB', 'GJBC', 'GJBD', 'GJCA',
                   'GJCB', 'GJCD', 'GJEA', 'GJEB', 'GJEC', 'GJED'],
            'GK': ['GKAA', 'GKAB', 'GKAC', 'GKAD', 'GKBA', 'GKBB', 'GKBD', 'GKCA', 'GKCB',
                   'GKCC', 'GKCD', 'GKEA', 'GKEB', 'GKEC', 'GKED'],
            'HA': ['HAAA', 'HAAB', 'HAAC', 'HAAD', 'HABA', 'HABB', 'HABD', 'HACA', 'HACB',
                   'HACD', 'HAEA', 'HAEB', 'HAED'],
            'HB': ['HBAA', 'HBAB', 'HBAC', 'HBAD', 'HBBA', 'HBBB', 'HBBD', 'HBCA', 'HBCB',
                   'HBCD', 'HBEA', 'HBEB', 'HBED'],
            'HC': ['HCAA', 'HCAB', 'HCAC', 'HCAD', 'HCBA', 'HCBB', 'HCBD', 'HCCA', 'HCCB',
                   'HCCD', 'HCEA', 'HCEB', 'HCEC', 'HCED'],
            'HD': ['HDAA', 'HDAB', 'HDAC', 'HDAD', 'HDBA', 'HDBB', 'HDBC', 'HDBD', 'HDCA',
                   'HDCB', 'HDCD', 'HDEA', 'HDEB', 'HDEC', 'HDED'],
            'HE': ['HEAA', 'HEAB', 'HEAC', 'HEAD', 'HEBA', 'HEBB', 'HEBC', 'HEBD', 'HECA',
                   'HECB', 'HECD', 'HEEA', 'HEEB', 'HEEC', 'HEED'],
            'HF': ['HFAA', 'HFAB', 'HFAC', 'HFAD', 'HFBA', 'HFBB', 'HFBD', 'HFCA', 'HFCB',
                   'HFCD', 'HFEA', 'HFEB', 'HFEC', 'HFED'],
            'HG': ['HGAA', 'HGAB', 'HGAC', 'HGAD', 'HGBA', 'HGBB', 'HGBD', 'HGCA', 'HGCB',
                   'HGCC', 'HGCD', 'HGEA', 'HGEB', 'HGEC', 'HGED'],
            'HH': ['HHAA', 'HHAB', 'HHAC', 'HHAD', 'HHBA', 'HHBB', 'HHBD', 'HHCA', 'HHCB',
                   'HHCC', 'HHCD', 'HHEA', 'HHEB', 'HHEC', 'HHED'],
            'HI': ['HIAA', 'HIAB', 'HIAC', 'HIAD', 'HIBA', 'HIBB', 'HIBC', 'HIBD', 'HICA',
                   'HICB', 'HICD', 'HIEA', 'HIEB', 'HIEC', 'HIED'],
            'HJ': ['HJAA', 'HJAB', 'HJAC', 'HJAD', 'HJBA', 'HJBB', 'HJBD', 'HJCA', 'HJCB',
                   'HJCD', 'HJEA', 'HJEB', 'HJEC', 'HJED'],
            'HK': ['HKAA', 'HKAB', 'HKAC', 'HKAD', 'HKBA', 'HKBB', 'HKBD', 'HKCA', 'HKCB',
                   'HKCD', 'HKEA', 'HKEB', 'HKEC', 'HKED'],
            'IA': ['IAAA', 'IAAB', 'IAAC', 'IAAD', 'IABA', 'IABB', 'IABD', 'IACA', 'IACB',
                   'IACD', 'IAEA', 'IAEB', 'IAED'],
            'IB': ['IBAA', 'IBAB', 'IBAC', 'IBAD', 'IBBA', 'IBBB', 'IBBD', 'IBCA', 'IBCB',
                   'IBCD', 'IBEA', 'IBEB', 'IBED'],
            'IC': ['ICAA', 'ICAB', 'ICAC', 'ICAD', 'ICBA', 'ICBB', 'ICBD', 'ICCA', 'ICCB',
                   'ICCC', 'ICCD', 'ICEA', 'ICEB', 'ICEC', 'ICED'],
            'ID': ['IDAA', 'IDAB', 'IDAC', 'IDAD', 'IDBA', 'IDBB', 'IDBD', 'IDCA', 'IDCB',
                   'IDCC', 'IDCD', 'IDEA', 'IDEB', 'IDED'],
            'IE': ['IEAA', 'IEAB', 'IEAC', 'IEAD', 'IEBA', 'IEBB', 'IEBD', 'IECA', 'IECB',
                   'IECD', 'IEEA', 'IEEB', 'IEEC', 'IEED'],
            'IF': ['IFAA', 'IFAB', 'IFAC', 'IFAD', 'IFBA', 'IFBB', 'IFBD', 'IFCA', 'IFCB',
                   'IFCD', 'IFEA', 'IFEB', 'IFEC', 'IFED'],
            'IG': ['IGAA', 'IGAB', 'IGAC', 'IGAD', 'IGBA', 'IGBB', 'IGBD', 'IGCA', 'IGCB',
                   'IGCD', 'IGEA', 'IGEB', 'IGEC', 'IGED'],
            'IH': ['IHAA', 'IHAB', 'IHAC', 'IHAD', 'IHBA', 'IHBB', 'IHBC', 'IHBD', 'IHCA',
                   'IHCB', 'IHCD', 'IHEA', 'IHEB', 'IHEC', 'IHED'],
            'II': ['IIAA', 'IIAB', 'IIAC', 'IIAD', 'IIBA', 'IIBB', 'IIBC', 'IIBD', 'IICA',
                   'IICB', 'IICC', 'IICD', 'IIEA', 'IIEB', 'IIEC', 'IIED'],
            'IJ': ['IJAA', 'IJAB', 'IJAC', 'IJAD', 'IJBA', 'IJBB', 'IJBC', 'IJBD', 'IJCA',
                   'IJCB', 'IJCC', 'IJCD', 'IJEA', 'IJEB', 'IJEC', 'IJED'],
            'IK': ['IKAA', 'IKAB', 'IKAC', 'IKAD', 'IKBA', 'IKBB', 'IKBD', 'IKCA', 'IKCB',
                   'IKCD', 'IKEA', 'IKEB', 'IKEC', 'IKED'],
            'JA': ['JAAA', 'JAAB', 'JAAC', 'JAAD', 'JABA', 'JABB', 'JABD', 'JACA', 'JACB',
                   'JACD', 'JAEA', 'JAEB', 'JAEC', 'JAED'],
            'JB': ['JBAA', 'JBAB', 'JBAC', 'JBAD', 'JBBA', 'JBBB', 'JBBD', 'JBCA', 'JBCB',
                   'JBCD', 'JBEA', 'JBEB', 'JBEC', 'JBED'],
            'JC': ['JCAA', 'JCAB', 'JCAC', 'JCAD', 'JCBA', 'JCBB', 'JCBC', 'JCBD', 'JCCA',
                   'JCCB', 'JCCD', 'JCEA', 'JCEB', 'JCED'],
            'JD': ['JDAA', 'JDAB', 'JDAC', 'JDAD', 'JDBA', 'JDBB', 'JDBC', 'JDBD', 'JDCA',
                   'JDCB', 'JDCC', 'JDCD', 'JDEA', 'JDEB', 'JDEC', 'JDED'],
            'JE': ['JEAA', 'JEAB', 'JEAC', 'JEAD', 'JEBA', 'JEBB', 'JEBD', 'JECA', 'JECB',
                   'JECD', 'JEEA', 'JEEB', 'JEEC', 'JEED'],
            'JF': ['JFAA', 'JFAB', 'JFAC', 'JFAD', 'JFBA', 'JFBB', 'JFBD', 'JFCA', 'JFCB',
                   'JFCC', 'JFCD', 'JFEA', 'JFEB', 'JFEC', 'JFED'],
            'JG': ['JGAA', 'JGAB', 'JGAC', 'JGAD', 'JGBA', 'JGBB', 'JGBC', 'JGBD', 'JGCA',
                   'JGCB', 'JGCD', 'JGEA', 'JGEB', 'JGEC', 'JGED'],
            'JH': ['JHAA', 'JHAB', 'JHAC', 'JHAD', 'JHBA', 'JHBB', 'JHBC', 'JHBD', 'JHCA',
                   'JHCB', 'JHCD', 'JHEA', 'JHEB', 'JHEC', 'JHED'],
            'JI': ['JIAA', 'JIAB', 'JIAC', 'JIAD', 'JIBA', 'JIBB', 'JIBC', 'JIBD', 'JICA',
                   'JICB', 'JICD', 'JIEA', 'JIEB', 'JIEC', 'JIED'],
            'JJ': ['JJAA', 'JJAB', 'JJAC', 'JJAD', 'JJBA', 'JJBB', 'JJBC', 'JJBD', 'JJCA',
                   'JJCB', 'JJCC', 'JJCD', 'JJEA', 'JJEB', 'JJEC', 'JJED'],
            'JK': ['JKAA', 'JKAB', 'JKAC', 'JKAD', 'JKBA', 'JKBB', 'JKBC', 'JKBD', 'JKCA',
                   'JKCB', 'JKCD', 'JKEA', 'JKEB', 'JKEC', 'JKED'],
            'KA': ['KAAA', 'KAAB', 'KAAC', 'KAAD', 'KABA', 'KABB', 'KABD', 'KACA', 'KACB',
                   'KACD', 'KAEA', 'KAEB', 'KAEC', 'KAED'],
            'KB': ['KBAA', 'KBAB', 'KBAC', 'KBAD', 'KBBA', 'KBBB', 'KBBD', 'KBCA', 'KBCB',
                   'KBCD', 'KBEA', 'KBEB', 'KBEC', 'KBED'],
            'KC': ['KCAA', 'KCAB', 'KCAC', 'KCAD', 'KCBA', 'KCBB', 'KCBC', 'KCBD', 'KCCA',
                   'KCCB', 'KCCC', 'KCCD', 'KCEA', 'KCEB', 'KCED'],
            'KD': ['KDAA', 'KDAB', 'KDAC', 'KDAD', 'KDBA', 'KDBB', 'KDBC', 'KDBD', 'KDCA',
                   'KDCB', 'KDCC', 'KDCD', 'KDEA', 'KDEB', 'KDEC', 'KDED'],
            'KE': ['KEAA', 'KEAB', 'KEAC', 'KEAD', 'KEBA', 'KEBB', 'KEBD', 'KECA', 'KECB',
                   'KECD', 'KEEA', 'KEEB', 'KEEC', 'KEED'],
            'KF': ['KFAA', 'KFAB', 'KFAC', 'KFAD', 'KFBA', 'KFBB', 'KFBD', 'KFCA', 'KFCB',
                   'KFCC', 'KFCD', 'KFEA', 'KFEB', 'KFEC', 'KFED'],
            'KG': ['KGAA', 'KGAB', 'KGAC', 'KGAD', 'KGBA', 'KGBB', 'KGBD', 'KGCA', 'KGCB',
                   'KGCC', 'KGCD', 'KGEA', 'KGEB', 'KGEC', 'KGED'],
            'KH': ['KHAA', 'KHAB', 'KHAC', 'KHAD', 'KHBA', 'KHBB', 'KHBD', 'KHCA', 'KHCB',
                   'KHCD', 'KHEA', 'KHEB', 'KHEC', 'KHED'],
            'KI': ['KIAA', 'KIAB', 'KIAC', 'KIAD', 'KIBA', 'KIBB', 'KIBD', 'KICA', 'KICB',
                   'KICC', 'KICD', 'KIEA', 'KIEB', 'KIEC', 'KIED'],
            'KJ': ['KJAA', 'KJAB', 'KJAC', 'KJAD', 'KJBA', 'KJBB', 'KJBC', 'KJBD', 'KJCA',
                   'KJCB', 'KJCC', 'KJCD', 'KJEA', 'KJEB', 'KJEC', 'KJED'],
            'KK': ['KKAA', 'KKAB', 'KKAC', 'KKAD', 'KKBA', 'KKBB', 'KKBC', 'KKBD', 'KKCA',
                   'KKCB', 'KKCC', 'KKCD', 'KKEA', 'KKEB', 'KKEC', 'KKED']}


def tranches_3d():
    """ Returns a dictionary with the names of zinc's 2D tranches

            Returns
            -------
            dict[str, list[str]]
    """
    path = PurePath(__file__).parent / "tranches.pickle"
    with open(path, "rb") as fp:
        tr = pickle.load(fp)
    return tr
